---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 林思宇.
--- DateTime: 2024/3/10 22:14
---
local voucherId = ARGV[1]
local userId = ARGV[2]

local stockKey = 'seckill:stock:'..voucherId
local orderKey = 'order:stock:'..voucherId
--判断库存是否充足
if(tonumber(redis.call('get',stockKey))<=0) then
    --库存不足，返回错误代码1
    return 1
end
--判断用户是否重复下单
if(redis.call('sismember',orderKey,userId)==1) then
    --存在，说明是重复下单，返回错误代码2
    return 2
end
redis.call('incrby',stockKey,-1)
redis.call('sadd',orderKey,userId)